### ISSUE TITLE
no such file or directory, chrome.zip

### ISSUE THREAD

**Issue by frellan** [jsreport/jsreport-dotnet#39]
I am encountering a strange error that I don't really know how to solve.

It works on a Ubuntu Server 18.04 but not on my local Mac. It has worked before and I have not changed any code. I recently upgraded the jsreport version.

> An unhandled exception has occurred while executing the request.
jsreport.Local.JsReportBinaryException: Error rendering report: A critical error occurred while trying to execute the render command: An error occurred while trying to start daemonized process: An error has occurred when trying to initialize jsreport (2). ENOENT: no such file or directory, open '/var/folders/vr/zx5vln4x4zj7wjg4trjsc4n00000gn/T/jsreport/compile/jsreport-2.6.1-HyhSOpsuH/chrome.zip' (1). caused by error (2) -> meta = {"code":"ENOENT"}, stack = Error:     at exports.initialize.instance.init.then.catch (/snapshot/jsreport/node_modules/jsreport-cli/lib/instanceHandler.js:31:29)caused by error (1) -> meta = {"errno":-2,"code":"ENOENT","syscall":"open","path":"/var/folders/vr/zx5vln4x4zj7wjg4trjsc4n00000gn/T/jsreport/compile/jsreport-2.6.1-HyhSOpsuH/chrome.zip"}, stack = Error:  (1). caused by error (1) -> meta = {"code":"ENOENT","disableExit":false}, stack = Error:     at exports.NsSocket.module.exports.socket.dataOnce (/snapshot/jsreport/node_modules/jsreport-cli/lib/keepAliveProcess.js:135:25)    at exports.NsSocket.listener (/snapshot/jsreport/node_modules/eventemitter2/lib/eventemitter2.js:251:10)    at exports.NsSocket.EventEmitter.emit (/snapshot/jsreport/node_modules/eventemitter2/lib/eventemitter2.js:339:22)    at exports.NsSocket._onData (/snapshot/jsreport/node_modules/nssocket/lib/nssocket.js:454:8)    at Lazy.<anonymous> (/snapshot/jsreport/node_modules/lazy/lazy.js:91:13)    at Lazy.<anonymous> (/snapshot/jsreport/node_modules/lazy/lazy.js:73:19)    at Lazy.emit (events.js:189:13)    at Lazy.<anonymous> (/snapshot/jsreport/node_modules/lazy/lazy.js:74:22)    at Lazy.emit (events.js:189:13)    at yieldTo (/snapshot/jsreport/node_modules/lazy/lazy.js:181:18)

I have this code to decide which binary to use:

```c#
var localReporting = new new LocalReporting();
if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
{
    localReporting.UseBinary(jsreport.Binary.OSX.JsReportBinary.GetBinary());
}
else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
{
    localReporting.UseBinary(jsreport.Binary.Linux.JsReportBinary.GetBinary());
}
else
{
    localReporting.UseBinary(jsreport.Binary.Linux.JsReportBinary.GetBinary());
}
```

**Comment by bjrmatos** [comment]
hmm that issue is a bit strange, because we are not deleting that chrome.zip at any part of the code. it makes me think that there is something in your machine that is deleting that file in your temp. do you know if there is something installed on your machine that can be deleting such files on temp?

can you please show me what are the files that you currently have at `/var/folders/vr/zx5vln4x4zj7wjg4trjsc4n00000gn/T/jsreport/compile/jsreport-2.6.1-HyhSOpsuH`? and the same for this path `/var/folders/vr/zx5vln4x4zj7wjg4trjsc4n00000gn/T/jsreport/compile`

from which jsreport version did you upgrade? 

as a quick fix that will let you move on, i will try the following:

- delete the `jsreport-2.6.1-HyhSOpsuH` folder at `/var/folders/vr/zx5vln4x4zj7wjg4trjsc4n00000gn/T/jsreport/compile`

- try to render again and check if you get an error

**Comment by alehro** [comment]
On Windows I suddenly started getting an exception that  there is no no such file or directory
c:\Users\Alex\AppData\Local\Temp\jsreport\compile\jsreport-2.6.1-HkSd-6jOS\chrome.zip 
After I deleted c:\Users\Alex\AppData\Local\Temp\jsreport\ directory all started working.

**Comment by pofider** [comment]
We have improved chrome unpacking in jsreport v3 sdk.
Please try to update and come back if you have still issues.
